# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='inseach',
            new_name='insearch',
        ),
    ]
