# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-21 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_clients_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='physicalCode',
            field=models.CharField(max_length=32, unique=True, verbose_name=b'Physical Code'),
        ),
    ]
