# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-26 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20160721_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birthDate',
            field=encrypted_fields.fields.EncryptedDateField(verbose_name=b'Birth Date (mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='insearch',
            field=models.BooleanField(default=False, verbose_name=b'In search'),
        ),
    ]
