# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20160726_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='physicalCode',
            field=models.CharField(max_length=32, verbose_name=b'Physical Code'),
        ),
    ]
