# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-27 17:45
from __future__ import unicode_literals

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20160727_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birthDate',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, verbose_name=b'Birth Date (mm/dd/yyyy)'),
        ),
    ]
