# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-27 18:56
from __future__ import unicode_literals

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20160727_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birthDate',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name=b'Birth Date (mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='identifier',
            field=encrypted_fields.fields.EncryptedCharField(max_length=9, unique=True, verbose_name=b'Identifier (for example, the passport id)'),
        ),
    ]
