# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160615_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='ref',
            field=models.IntegerField(verbose_name=b'Ref.Point'),
        ),
    ]
