# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-27 20:58
from __future__ import unicode_literals

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20160720_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='tmpLat',
            field=encrypted_fields.fields.EncryptedCharField(default=0, max_length=30, verbose_name=b'Tmp Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='tmpLng',
            field=encrypted_fields.fields.EncryptedCharField(default=0, max_length=30, verbose_name=b'Tmp Longitude'),
            preserve_default=False,
        ),
    ]
