# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-30 12:52
from __future__ import unicode_literals

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20160727_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='initialWp',
            field=encrypted_fields.fields.EncryptedIntegerField(default=0, verbose_name=b'Initial Waypoints in Route'),
            preserve_default=False,
        ),
    ]
