# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droneRef', encrypted_fields.fields.EncryptedCharField(max_length=20, verbose_name='Ref')),
                ('preSharedKey', encrypted_fields.fields.EncryptedCharField(max_length=100, unique=True, verbose_name='Pre-Shared Key')),
                ('droneSpeed', encrypted_fields.fields.EncryptedIntegerField(verbose_name='Drone Speed')),
            ],
        ),
    ]
