# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='preSharedKey',
        ),
    ]
