# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-26 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_remove_drone_presharedkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='droneSpeed',
        ),
    ]
